
D=0
R=1

# Data:
state_history = [
[R,D,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,D,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,D,R,R,R,D,D],
[R,R,R,R,R,D,D,D,D,D,D],
[R,D,R,R,R,D,D,D,D,D,D],
[D,D,D,D,D,D,D,D,D,D,D],
[R,D,R,R,R,R,D,R,R,D,D],
[R,D,D,R,R,D,R,R,R,R,R],
[R,D,D,R,D,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,D,R],
[R,R,R,R,D,D,D,D,R,D,D],
[R,R,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,D,D,R,R,D,D,D,D,D,D],
[D,D,R,R,D,D,D,D,D,D,D],
[R,R,R,R,R,D,D,D,D,D,D],
[R,D,D,D,D,D,D,D,D,D,D],
[R,D,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,R,R,R,R,D,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,D,D,R,R,D,D],
[R,R,R,R,R,D,D,R,D,D,D],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,D,D,D,R,D,D],
[R,D,R,R,D,D,D,D,D,D,D],
[R,D,R,R,R,R,R,R,R,D,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,D,D],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,D,D,D,D,D,D,D],
[R,D,R,R,R,D,D,D,D,D,D],
[R,D,D,R,D,D,D,D,D,D,D],
[R,D,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,D,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,D,D],
[R,R,R,R,D,D,D,D,D,D,D],
[R,D,D,R,D,D,D,R,R,R,R],
[R,D,R,R,D,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,R,R]]

# State names
state_names = [
"Alabama",
"Alaska",
"Arizona",
"Arkansas",
"California",
"Colorado",
"Connecticut",
"Delaware",
"D.C.",
"Florida",
"Georgia",
"Hawaii",
"Idaho",
"Illinois",
"Indiana",
"Iowa",
"Kansas",
"Kentucky",
"Louisiana",
"Maine",
"Maryland",
"Massachusetts",
"Michigan",
"Minnesota",
"Mississippi",
"Missouri",
"Montana",
"Nebraska",
"Nevada",
"New Hampshire",
"New Jersey",
"New Mexico",
"New York",
"North Carolina",
"North Dakota",
"Ohio",
"Oklahoma",
"Oregon",
"Pennsylvania",
"Rhode Island",
"South Carolina",
"South Dakota",
"Tennessee",
"Texas",
"Utah",
"Vermont",
"Virginia",
"Washington",
"West Virginia",
"Wisconsin",
"Wyoming"]